export const somertonRoutes = {
  1: {
    name: "Melbourne to Dimboola",
    stations: ["Melbourne", "Rockbank", "Gordon", "Ouyen", "Ararat", "Beulah", "Antwerp", "Bordertown", "Dimboola"],
    path: ["Melbourne", "Rockbank", "Gordon", "Ouyen", "Ararat", "Beulah", "Antwerp", "Bordertown", "Dimboola"],
  },
  2: {
    name: "Melbourne to Panitya",
    stations: [
      "Melbourne",
      "Tallarook",
      "Bendigo",
      "Inglewood",
      "Malmsbury",
      "Pyalong",
      "Arnold",
      "Navarre",
      "Elmhurst",
      "Tatyoon",
      "Panitya",
    ],
    path: [
      "Melbourne",
      "Tallarook",
      "Bendigo",
      "Inglewood",
      "Malmsbury",
      "Pyalong",
      "Arnold",
      "Navarre",
      "Elmhurst",
      "Tatyoon",
      "Panitya",
    ],
  },
  3: {
    name: "Melbourne to Callington",
    stations: [
      "Melbourne",
      "Lexton",
      "Inglewood",
      "Ararat",
      "Bordertown",
      "Ouyen",
      "Apsley",
      "Irymple",
      "Alawoona",
      "Qualco",
      "Callington",
    ],
    path: [
      "Melbourne",
      "Lexton",
      "Inglewood",
      "Ararat",
      "Bordertown",
      "Ouyen",
      "Apsley",
      "Irymple",
      "Alawoona",
      "Qualco",
      "Callington",
    ],
  },
  4: {
    name: "Islington to Bordertown",
    stations: [
      "Islington",
      "Tailem Bend",
      "Tintinara",
      "Meningie",
      "Tatiara",
      "Serviceton",
      "Apsley",
      "Mundulla",
      "Serviceton",
      "Tatiara",
      "Geranium",
      "Alawoona",
      "Bordertown",
    ],
    path: [
      "Islington",
      "Tailem_Bend",
      "Tintinara",
      "Meningie",
      "Tatiara",
      "Serviceton",
      "Apsley",
      "Mundulla",
      "Serviceton",
      "Tatiara",
      "Geranium",
      "Alawoona",
      "Bordertown",
    ],
  },
}

export const zhanjiangRoutes = {
  1: {
    name: "黎湛铁路",
    stations: ["湛江站", "遂溪站", "廉江站", "河唇站"],
    path: ["湛江站", "遂溪站", "廉江站", "河唇站"],
  },
  2: {
    name: "粤海铁路",
    stations: ["湛江站", "塘缀站", "雷州站", "雷州龙门站", "徐闻站"],
    path: ["湛江站", "塘缀站", "雷州站", "雷州龙门站", "徐闻站"],
  },
  3: {
    name: "深湛铁路",
    stations: ["湛江西站", "湛江站"],
    path: ["湛江西站", "湛江站"],
  },
  4: {
    name: "广湛高铁(在建)",
    stations: ["湛江北站", "湛江西站"],
    path: ["湛江北站", "湛江西站"],
  },
  5: {
    name: "河茂铁路",
    stations: ["河唇站", "廉江站"],
    path: ["河唇站", "廉江站"],
  },
}

// 删除不需要的代码行
export const somertonCodeLines = []
